### ISSUE TITLE
Public - View main landing page ("Welcome to BetterVote")

### ISSUE THREAD

**Issue by amaidah** [amaidah/better-vote#2]
As a public visitor, I want to see some basic website stuff at better.vote, so I know that BetterVote is not a scam.

* Good enough that it just says "Welcome to BetterVote" at the top. If you want to dump in some basic templating, that's fine.

**Comment by hegemonia** [comment]
This is mainly just the plumbing story, but a user should be able to hit a functioning website. Maybe not quite at better.vote for now, but at some holding url (are we using Heroku?).

**Comment by amaidah** [comment]
yea heroku, can use bettervote.today so that i can learn to map emails to a
custom domain

**Comment by amaidah** [comment]
in fact, i'm not sure if email services will let you send emails from a random url. probably have to have a custom domain

**Comment by hegemonia** [comment]
Updated this so that it includes a working better.vote
